version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cart-microservice
    ports:
      - 8090:8090
    volumes:
      - ./config.json:/src/config.json